/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Bridge */

#ifndef _Included_Bridge
#define _Included_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Bridge
 * Method:    recognize
 * Signature: ([FI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Bridge_recognize
  (JNIEnv *, jobject, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
