#define HAVE_ARPA_INET_H 1
#define HAVE_ARPA_NAMESER_COMPAT_H 1
/* #undef HAVE_CORESERVICES_CORESERVICES_H */
#define HAVE_CPUID_H 1
#define HAVE_CTYPE_H 1
#define HAVE_DLFCN_H 1
#define HAVE_ENDIAN_H 1
#define HAVE_ERRNO_H 1
#define HAVE_FCNTL_H 1
#define HAVE_FLOAT_H 1
#define HAVE_ICONV_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_LANGINFO_H 1
#define HAVE_LIMITS_H 1
#define HAVE_LOCALE_H 1
/* #undef HAVE_MACHINE_ENDIAN_H */
#define HAVE_MEMORY_H 1
/* #undef HAVE_NETDB_H */
/* #undef HAVE_NETINET_IN_H */
/* #undef HAVE_NL_TYPES_H */
/* #undef HAVE_STDBOOL_H */
/* #undef HAVE_STDDEF_H */
/* #undef HAVE_STDINT_H */
/* #undef HAVE_STDIO_H */
/* #undef HAVE_STDLIB_H */
/* #undef HAVE_STRINGS_H */
/* #undef HAVE_STRING_H */
/* #undef HAVE_SYS_PARAM_H */
/* #undef HAVE_SYS_SOCKET_H */
/* #undef HAVE_SYS_STAT_H */
/* #undef HAVE_SYS_TIMEB_H */
#define HAVE_SYS_TIME_H 1
/* #undef HAVE_SYS_TYPES_H */
#define HAVE_UNISTD_H 1
#define HAVE_WCHAR_H 1
#define HAVE_WCTYPE_H 1
/* #undef HAVE_WINSOCK2_H */
/* #undef XERCES_HAVE_EMMINTRIN_H */
/* #undef XERCES_HAVE_INTRIN_H */
/* #undef XERCES_HAVE_INTTYPES_H */
/* #undef XERCES_HAVE_SYS_TYPES_H */
/* #undef XERCES_INCLUDE_WCHAR_H */

// Functions Symbols
/* #undef HAVE_BOOL */
/* #undef HAVE_CATCLOSE */
#define HAVE_CATGETS 1
#define HAVE_CATOPEN 1
#define HAVE_CLOCK_GETTIME 1
#define HAVE_FTIME 1
#define HAVE_GETADDRINFO 1
#define HAVE_GETCWD 1
#define HAVE_GETHOSTBYADDR 1
#define HAVE_GETHOSTBYNAME 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_ICONV 1
#define HAVE_ICONV_CLOSE 1
#define HAVE_ICONV_OPEN 1
/* #undef HAVE_LIBNSL */
/* #undef HAVE_LIBSOCKET */
#define HAVE_LOCALECONV 1
/* #undef HAVE_LSTRING */
#define HAVE_MBLEN 1
#define HAVE_MBRLEN 1
/* #undef HAVE_MBSRTOWCS */
/* #undef HAVE_MBSTOWCS */
#define HAVE_MEMMOVE 1
/* #undef HAVE_MEMSET */
/* #undef HAVE_NAMESPACES */
/* #undef HAVE_NL_LANGINFO */
/* #undef HAVE_PATHCONF */
/* #undef HAVE_PATH_MAX */
/* #undef HAVE_PTHREAD */
/* #undef HAVE_REALPATH */
/* #undef HAVE_SETLOCALE */
/* #undef HAVE_SOCKET */
/* #undef HAVE_STD_LIBS */
/* #undef HAVE_STD_NAMESPACE */
#define HAVE_STRCASECMP 1
/* #undef HAVE_STRCHR */
#define HAVE_STRDUP 1
/* #undef HAVE_STRICMP */
#define HAVE_STRNCASECMP 1
/* #undef HAVE_STRNICMP */
/* #undef HAVE_STRRCHR */
/* #undef HAVE_STRSTR */
/* #undef HAVE_STRTOL */
/* #undef HAVE_STRTOUL */
#define HAVE_TOWLOWER 1
#define HAVE_TOWUPPER 1
/* #undef HAVE_WCSICMP */
/* #undef HAVE_WCSLWR */
/* #undef HAVE_WCSNICMP */
/* #undef HAVE_WCSRTOMBS */
/* #undef HAVE_WCSTOMBS */
/* #undef HAVE_WCSUPR */
/* #undef HAVE__BOOL */
/* #undef XERCES_HAVE_CPUID_INTRINSIC */
/* #undef XERCES_HAVE_GETCPUID */
/* #undef XERCES_HAVE_SSE2_INTRINSIC */



//#define XERCES_USE_FILEMGR_POSIX 1
#define XERCES_USE_FILEMGR_POSIX 1
/* #undef XERCES_USE_FILEMGR_WINDOWS */
/* #undef XERCES_USE_MSGLOADER_ICONV */
/* #undef XERCES_USE_MSGLOADER_ICONV */
/* #undef XERCES_USE_MSGLOADER_ICU */
#define XERCES_USE_MSGLOADER_INMEMORY 1
/* #undef XERCES_USE_MUTEXMGR_NOTHREAD */
//#define XERCES_USE_MUTEXMGR_POSIX 1
#define XERCES_USE_MUTEXMGR_POSIX 1
/* #undef XERCES_USE_MUTEXMGR_WINDOWS */
/* #undef XERCES_USE_NETACCESSOR_CFURL */
/* #undef XERCES_USE_NETACCESSOR_CURL */
/* #undef XERCES_USE_NETACCESSOR_CURL */
/* #undef XERCES_USE_NETACCESSOR_SOCKET */
/* #undef XERCES_USE_NETACCESSOR_WINSOCK */
//#define XERCES_USE_TRANSCODER_GNUICONV 1
#define XERCES_USE_TRANSCODER_GNUICONV 1
/* #undef XERCES_USE_TRANSCODER_ICONV */
/* #undef XERCES_USE_TRANSCODER_ICU */
/* #undef XERCES_USE_TRANSCODER_MACOSUNICODECONVERTER */
/* #undef XERCES_USE_TRANSCODER_WINDOWS */
/* #undef XERCES_XMLCH_T */
